version: '3.9'

networks:
  example-db-network:
    name: example-db-network

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./.volume/mongo:/data/db
    networks:
      - example-db-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 8081:8081
    networks:
      - example-db-network
    restart: on-failure:5

  db-backup:
    image: tiredofit/db-backup
    environment:
      - DB_TYPE=mongo
      - DB_NAME=ALL
      - SPLIT_DB=TRUE
      - MONGO_CUSTOM_URI=mongodb://mongo:27017
      - COMPRESSION=GZ
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEBUG_MODE=FALSE
    ports:
      - 10050:10050
      - 2020:2020
    networks:
      - example-db-network
    volumes:
      - ./.volume/db-backup:/backup
